fail_fast: false
repos:
  - repo: 'https://github.com/pocc/pre-commit-hooks'
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=Google]
      - id: cppcheck
        args: [--language=c++, --suppressions-list=./.suppress.cppcheck]
      - id: cpplint
        name: Static code checker for C++
        args: [--linelength=85, --root=src, --extensions=cpp]

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys', "--indent=2"]

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.1.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
